import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // ⬅️ ACTUALIZADO: Definir colors personalitzats que Tailwind reconegui
        purple: {
          25: "#faf7ff",
          125: "#f0e7ff", // ⬅️ NUEVO: Color del mig per botons
          150: "#e9d5ff",
          175: "#e0d1ff", // ⬅️ NUEVO: Color per hover
        },
        pink: {
          25: "#fef9fc",
          125: "#fdf2f8",
          150: "#fce7f3",
          175: "#fce7f3",
        },
        cyan: {
          25: "#f7feff",
          125: "#e6fffa",
          150: "#cffafe",
          175: "#cffafe",
        },
        blue: {
          25: "#f7fbff",
          125: "#eff6ff",
          150: "#dbeafe",
          175: "#dbeafe",
        },
        sky: {
          25: "#f7fcff",
          125: "#f0f9ff",
          150: "#e0f2fe",
          175: "#e0f2fe",
        },
        teal: {
          25: "#f7fffe",
          125: "#f0fdfa",
          150: "#ccfbf1",
          175: "#ccfbf1",
        },
        green: {
          25: "#f7fef7",
          125: "#f0fdf4",
          150: "#dcfce7",
          175: "#dcfce7",
        },
        emerald: {
          25: "#f7fef9",
          125: "#ecfdf5",
          150: "#d1fae5",
          175: "#d1fae5",
        },
        lime: {
          25: "#fbfef7",
          125: "#f7fee7",
          150: "#ecfccb",
          175: "#ecfccb",
        },
        yellow: {
          25: "#fffef7",
          150: "#fef3c7",
        },
        amber: {
          25: "#fffcf7",
          150: "#fde68a",
        },
        orange: {
          25: "#fffaf7",
          150: "#fed7aa",
        },
        red: {
          25: "#fffaf7",
          125: "#fef2f2", // ⬅️ NUEVO: Per botons destructius
          150: "#fecaca",
          175: "#fee2e2", // ⬅️ NUEVO: Per hover destructiu
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  // ⬅️ ACTUALIZADO: Assegurar que Tailwind generi totes les classes que necessitem
  safelist: [
    // Colors de text
    "text-purple-400",
    "text-purple-500",
    "text-purple-600",
    "text-purple-700", // ⬅️ NUEVO
    "text-pink-400",
    "text-pink-500",
    "text-pink-600",
    "text-pink-700", // ⬅️ NUEVO
    "text-cyan-400",
    "text-cyan-500",
    "text-cyan-600",
    "text-cyan-700", // ⬅️ NUEVO
    "text-blue-400",
    "text-blue-500",
    "text-blue-600",
    "text-blue-700", // ⬅️ NUEVO
    "text-sky-400",
    "text-sky-500",
    "text-sky-600",
    "text-sky-700", // ⬅️ NUEVO
    "text-teal-400",
    "text-teal-500",
    "text-teal-600",
    "text-teal-700", // ⬅️ NUEVO
    "text-green-400",
    "text-green-500",
    "text-green-600",
    "text-green-700", // ⬅️ NUEVO
    "text-emerald-400",
    "text-emerald-500",
    "text-emerald-600",
    "text-emerald-700", // ⬅️ NUEVO
    "text-lime-400",
    "text-lime-500",
    "text-lime-600",
    "text-lime-700", // ⬅️ NUEVO
    "text-red-700", // ⬅️ NUEVO

    // ⬅️ NUEVO: Backgrounds plans per botons
    "bg-purple-125",
    "bg-pink-125",
    "bg-cyan-125",
    "bg-blue-125",
    "bg-sky-125",
    "bg-teal-125",
    "bg-green-125",
    "bg-emerald-125",
    "bg-lime-125",
    "bg-red-125",

    // ⬅️ NUEVO: Hover backgrounds
    "bg-purple-175",
    "bg-pink-175",
    "bg-cyan-175",
    "bg-blue-175",
    "bg-sky-175",
    "bg-teal-175",
    "bg-green-175",
    "bg-emerald-175",
    "bg-lime-175",
    "bg-red-175",

    "hover:bg-purple-125",
    "hover:bg-pink-125",
    "hover:bg-cyan-125",
    "hover:bg-blue-125",
    "hover:bg-sky-125",
    "hover:bg-teal-125",
    "hover:bg-green-125",
    "hover:bg-emerald-125",
    "hover:bg-lime-125",
    "hover:bg-red-125",

    "hover:bg-purple-175",
    "hover:bg-pink-175",
    "hover:bg-cyan-175",
    "hover:bg-blue-175",
    "hover:bg-sky-175",
    "hover:bg-teal-175",
    "hover:bg-green-175",
    "hover:bg-emerald-175",
    "hover:bg-lime-175",
    "hover:bg-red-175",

    // Borders
    "border-purple-150",
    "border-purple-200",
    "border-purple-300",
    "border-pink-150",
    "border-pink-200",
    "border-pink-300",
    "border-cyan-150",
    "border-cyan-200",
    "border-cyan-300",
    "border-blue-150",
    "border-blue-200",
    "border-blue-300",
    "border-sky-150",
    "border-sky-200",
    "border-sky-300",
    "border-teal-150",
    "border-teal-200",
    "border-teal-300",
    "border-green-150",
    "border-green-200",
    "border-green-300",
    "border-emerald-150",
    "border-emerald-200",
    "border-emerald-300",
    "border-lime-150",
    "border-lime-200",
    "border-lime-300",

    // Focus borders
    "focus:border-purple-300",
    "focus:border-pink-300",
    "focus:border-cyan-300",
    "focus:border-blue-300",
    "focus:border-sky-300",
    "focus:border-teal-300",
    "focus:border-green-300",
    "focus:border-emerald-300",
    "focus:border-lime-300",

    // Gradients from
    "from-purple-100",
    "from-purple-150",
    "from-purple-200",
    "from-pink-100",
    "from-pink-150",
    "from-pink-200",
    "from-cyan-100",
    "from-cyan-150",
    "from-cyan-200",
    "from-blue-100",
    "from-blue-150",
    "from-blue-200",
    "from-sky-100",
    "from-sky-150",
    "from-sky-200",
    "from-teal-100",
    "from-teal-150",
    "from-teal-200",
    "from-green-100",
    "from-green-150",
    "from-green-200",
    "from-emerald-100",
    "from-emerald-150",
    "from-emerald-200",
    "from-lime-100",
    "from-lime-150",
    "from-lime-200",

    // Gradients to
    "to-purple-100",
    "to-purple-150",
    "to-purple-200",
    "to-pink-100",
    "to-pink-150",
    "to-pink-200",
    "to-cyan-100",
    "to-cyan-150",
    "to-cyan-200",
    "to-blue-100",
    "to-blue-150",
    "to-blue-200",
    "to-sky-100",
    "to-sky-150",
    "to-sky-200",
    "to-teal-100",
    "to-teal-150",
    "to-teal-200",
    "to-green-100",
    "to-green-150",
    "to-green-200",
    "to-emerald-100",
    "to-emerald-150",
    "to-emerald-200",
    "to-lime-100",
    "to-lime-150",
    "to-lime-200",

    // Gradients via
    "via-purple-25",
    "via-pink-25",
    "via-cyan-25",
    "via-blue-25",
    "via-sky-25",
    "via-teal-25",
    "via-green-25",
    "via-emerald-25",
    "via-lime-25",
    "via-yellow-25",
    "via-amber-25",
    "via-orange-25",
    "via-red-25",

    // Background gradients
    "from-purple-50",
    "from-pink-50",
    "from-cyan-50",
    "from-blue-50",
    "from-sky-50",
    "from-teal-50",
    "from-green-50",
    "from-emerald-50",
    "from-lime-50",
    "from-yellow-50",
    "from-amber-50",
    "from-orange-50",
    "from-red-50",

    "to-purple-50",
    "to-pink-50",
    "to-cyan-50",
    "to-blue-50",
    "to-sky-50",
    "to-teal-50",
    "to-green-50",
    "to-emerald-50",
    "to-lime-50",
    "to-yellow-50",
    "to-amber-50",
    "to-orange-50",
    "to-red-50",

    // Hover states
    "hover:from-purple-150",
    "hover:from-purple-200",
    "hover:from-pink-150",
    "hover:from-pink-200",
    "hover:from-cyan-150",
    "hover:from-cyan-200",
    "hover:from-blue-150",
    "hover:from-blue-200",
    "hover:from-sky-150",
    "hover:from-sky-200",
    "hover:from-teal-150",
    "hover:from-teal-200",
    "hover:from-green-150",
    "hover:from-green-200",
    "hover:from-emerald-150",
    "hover:from-emerald-200",
    "hover:from-lime-150",
    "hover:from-lime-200",

    "hover:to-purple-150",
    "hover:to-purple-200",
    "hover:to-pink-150",
    "hover:to-pink-200",
    "hover:to-cyan-150",
    "hover:to-cyan-200",
    "hover:to-blue-150",
    "hover:to-blue-200",
    "hover:to-sky-150",
    "hover:to-sky-200",
    "hover:to-teal-150",
    "hover:to-teal-200",
    "hover:to-green-150",
    "hover:to-green-200",
    "hover:to-emerald-150",
    "hover:to-emerald-200",
    "hover:to-lime-150",
    "hover:to-lime-200",
  ],
}

export default config
